/**
 * Copyright (C) 2014 BigLoupe http://bigloupe.github.io/SoS-JobScheduler/
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License
 */
/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.17 at 03:00:56 PM MEZ 
//


package com.sos.scheduler.model.objects;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

import com.sos.scheduler.model.commands.AddJobs;
import com.sos.scheduler.model.commands.CheckFolders;
import com.sos.scheduler.model.commands.JobChainModify;
import com.sos.scheduler.model.commands.JobChainNodeModify;
import com.sos.scheduler.model.commands.KillTask;
import com.sos.scheduler.model.commands.LicenceUse;
import com.sos.scheduler.model.commands.LockRemove;
import com.sos.scheduler.model.commands.ModifyHotFolder;
import com.sos.scheduler.model.commands.ModifyJob;
import com.sos.scheduler.model.commands.ModifyOrder;
import com.sos.scheduler.model.commands.ModifySpooler;
import com.sos.scheduler.model.commands.ProcessClassRemove;
import com.sos.scheduler.model.commands.RemoteSchedulerRemoteTaskClose;
import com.sos.scheduler.model.commands.RemoteSchedulerStartRemoteTask;
import com.sos.scheduler.model.commands.RemoveJobChain;
import com.sos.scheduler.model.commands.RemoveOrder;
import com.sos.scheduler.model.commands.SchedulerLogLogCategoriesReset;
import com.sos.scheduler.model.commands.SchedulerLogLogCategoriesSet;
import com.sos.scheduler.model.commands.ShowCalendar;
import com.sos.scheduler.model.commands.ShowHistory;
import com.sos.scheduler.model.commands.ShowJob;
import com.sos.scheduler.model.commands.ShowJobChain;
import com.sos.scheduler.model.commands.ShowJobChains;
import com.sos.scheduler.model.commands.ShowJobs;
import com.sos.scheduler.model.commands.ShowOrder;
import com.sos.scheduler.model.commands.ShowState;
import com.sos.scheduler.model.commands.ShowTask;
import com.sos.scheduler.model.commands.StartJob;
import com.sos.scheduler.model.commands.SubsystemShow;
import com.sos.scheduler.model.commands.Terminate;


/**
 * <p>Java class for Commands complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Commands">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}add_jobs"/>
 *         &lt;element ref="{}add_order"/>
 *         &lt;element name="check_folders" type="{}check_folders"/>
 *         &lt;element ref="{}kill_task"/>
 *         &lt;element ref="{}licence.use"/>
 *         &lt;element name="lock" type="{}lock"/>
 *         &lt;element name="lock.remove" type="{}lock.remove"/>
 *         &lt;element ref="{}modify_job"/>
 *         &lt;element ref="{}modify_hot_folder"/>
 *         &lt;element ref="{}modify_order"/>
 *         &lt;element ref="{}modify_spooler"/>
 *         &lt;element ref="{}job_chain.modify"/>
 *         &lt;element ref="{}job_chain_node.modify"/>
 *         &lt;element name="order" type="{}order"/>
 *         &lt;element name="process_class" type="{}process_class"/>
 *         &lt;element name="process_class.remove" type="{}process_class.remove"/>
 *         &lt;element ref="{}register_remote_scheduler"/>
 *         &lt;element ref="{}remove_job_chain"/>
 *         &lt;element ref="{}remove_order"/>
 *         &lt;element name="run_time" type="{}run_time"/>
 *         &lt;element ref="{}scheduler_log.log_categories.reset"/>
 *         &lt;element ref="{}scheduler_log.log_categories.set"/>
 *         &lt;element ref="{}scheduler_log.log_categories.show"/>
 *         &lt;element ref="{}show_calendar"/>
 *         &lt;element ref="{}show_history"/>
 *         &lt;element ref="{}show_job"/>
 *         &lt;element ref="{}show_jobs"/>
 *         &lt;element ref="{}show_job_chains"/>
 *         &lt;element ref="{}show_job_chain"/>
 *         &lt;element ref="{}show_order"/>
 *         &lt;element ref="{}s"/>
 *         &lt;element ref="{}show_schedulers"/>
 *         &lt;element ref="{}show_state"/>
 *         &lt;element ref="{}show_task"/>
 *         &lt;element ref="{}service_request"/>
 *         &lt;element ref="{}start_job"/>
 *         &lt;element ref="{}subsystem.show"/>
 *         &lt;element ref="{}remote_scheduler.start_remote_task"/>
 *         &lt;element ref="{}remote_scheduler.remote_task.close"/>
 *         &lt;element ref="{}terminate"/>
 *       &lt;/choice>
 *       &lt;attribute name="on_exit_code">
 *         &lt;simpleType>
 *           &lt;union>
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                 &lt;enumeration value="success"/>
 *                 &lt;enumeration value="error"/>
 *                 &lt;enumeration value="signal"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *             &lt;simpleType>
 *               &lt;list>
 *                 &lt;simpleType>
 *                   &lt;union>
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                     &lt;simpleType>
 *                       &lt;restriction base="{}Unix_signal_name">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/union>
 *                 &lt;/simpleType>
 *               &lt;/list>
 *             &lt;/simpleType>
 *           &lt;/union>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Commands", propOrder = {
    "addJobsOrAddOrderOrCheckFolders"
})
public class Commands extends JSObjBase {

    @XmlElementRefs({
        @XmlElementRef(name = "licence.use", type = LicenceUse.class),
        @XmlElementRef(name = "show_history", type = ShowHistory.class),
        @XmlElementRef(name = "terminate", type = Terminate.class),
        @XmlElementRef(name = "show_jobs", type = ShowJobs.class),
        @XmlElementRef(name = "show_task", type = ShowTask.class),
        @XmlElementRef(name = "show_job", type = ShowJob.class),
        @XmlElementRef(name = "run_time", type = JAXBElement.class),
        @XmlElementRef(name = "modify_order", type = ModifyOrder.class),
        @XmlElementRef(name = "modify_job", type = ModifyJob.class),
        @XmlElementRef(name = "scheduler_log.log_categories.set", type = SchedulerLogLogCategoriesSet.class),
        @XmlElementRef(name = "process_class", type = JAXBElement.class),
        @XmlElementRef(name = "modify_spooler", type = ModifySpooler.class),
        @XmlElementRef(name = "remote_scheduler.start_remote_task", type = RemoteSchedulerStartRemoteTask.class),
        @XmlElementRef(name = "subsystem.show", type = JAXBElement.class),
        @XmlElementRef(name = "lock", type = JAXBElement.class),
        @XmlElementRef(name = "remove_job_chain", type = RemoveJobChain.class),
        @XmlElementRef(name = "order", type = JAXBElement.class),
        @XmlElementRef(name = "lock.remove", type = JAXBElement.class),
        @XmlElementRef(name = "remote_scheduler.remote_task.close", type = RemoteSchedulerRemoteTaskClose.class),
        @XmlElementRef(name = "show_state", type = JAXBElement.class),
        @XmlElementRef(name = "scheduler_log.log_categories.reset", type = SchedulerLogLogCategoriesReset.class),
        @XmlElementRef(name = "show_job_chain", type = ShowJobChain.class),
        @XmlElementRef(name = "job_chain.modify", type = JobChainModify.class),
        @XmlElementRef(name = "remove_order", type = RemoveOrder.class),
        @XmlElementRef(name = "show_order", type = ShowOrder.class),
        @XmlElementRef(name = "add_order", type = JAXBElement.class),
        @XmlElementRef(name = "job_chain_node.modify", type = JobChainNodeModify.class),
        @XmlElementRef(name = "process_class.remove", type = JAXBElement.class),
        @XmlElementRef(name = "start_job", type = StartJob.class),
        @XmlElementRef(name = "show_schedulers", type = JAXBElement.class),
        @XmlElementRef(name = "show_calendar", type = ShowCalendar.class),
        @XmlElementRef(name = "modify_hot_folder", type = JAXBElement.class),
        @XmlElementRef(name = "scheduler_log.log_categories.show", type = JAXBElement.class),
        @XmlElementRef(name = "register_remote_scheduler", type = RegisterRemoteScheduler.class),
        @XmlElementRef(name = "show_job_chains", type = ShowJobChains.class),
        @XmlElementRef(name = "add_jobs", type = AddJobs.class),
        @XmlElementRef(name = "service_request", type = ServiceRequest.class),
        @XmlElementRef(name = "kill_task", type = KillTask.class),
        @XmlElementRef(name = "check_folders", type = JAXBElement.class),
        @XmlElementRef(name = "s", type = JAXBElement.class)
    })
    protected List<Object> addJobsOrAddOrderOrCheckFolders;
    @XmlAttribute(name = "on_exit_code")
    protected List<String> onExitCode;

    /**
     * Gets the value of the addJobsOrAddOrderOrCheckFolders property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addJobsOrAddOrderOrCheckFolders property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddJobsOrAddOrderOrCheckFolders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShowHistory }
     * {@link LicenceUse }
     * {@link Terminate }
     * {@link ShowJobs }
     * {@link ShowTask }
     * {@link ShowJob }
     * {@link ModifyOrder }
     * {@link JAXBElement }{@code <}{@link RunTime }{@code >}
     * {@link SchedulerLogLogCategoriesSet }
     * {@link ModifyJob }
     * {@link ModifySpooler }
     * {@link JAXBElement }{@code <}{@link ProcessClass }{@code >}
     * {@link RemoteSchedulerStartRemoteTask }
     * {@link JAXBElement }{@code <}{@link SubsystemShow }{@code >}
     * {@link JAXBElement }{@code <}{@link Lock }{@code >}
     * {@link RemoveJobChain }
     * {@link JAXBElement }{@code <}{@link LockRemove }{@code >}
     * {@link JAXBElement }{@code <}{@link Order }{@code >}
     * {@link RemoteSchedulerRemoteTaskClose }
     * {@link JAXBElement }{@code <}{@link ShowState }{@code >}
     * {@link SchedulerLogLogCategoriesReset }
     * {@link ShowJobChain }
     * {@link JobChainModify }
     * {@link RemoveOrder }
     * {@link StartJob }
     * {@link JAXBElement }{@code <}{@link ProcessClassRemove }{@code >}
     * {@link JobChainNodeModify }
     * {@link JAXBElement }{@code <}{@link Order }{@code >}
     * {@link ShowOrder }
     * {@link JAXBElement }{@code <}{@link ShowState }{@code >}
     * {@link JAXBElement }{@code <}{@link ModifyHotFolder }{@code >}
     * {@link ShowCalendar }
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link RegisterRemoteScheduler }
     * {@link AddJobs }
     * {@link ShowJobChains }
     * {@link ServiceRequest }
     * {@link KillTask }
     * {@link JAXBElement }{@code <}{@link CheckFolders }{@code >}
     * {@link JAXBElement }{@code <}{@link ShowState }{@code >}
     * 
     * 
     */
    public List<Object> getAddJobsOrAddOrderOrCheckFolders() {
        if (addJobsOrAddOrderOrCheckFolders == null) {
            addJobsOrAddOrderOrCheckFolders = new ArrayList<Object>();
        }
        return this.addJobsOrAddOrderOrCheckFolders;
    }

    /**
     * Gets the value of the onExitCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the onExitCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOnExitCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOnExitCode() {
        if (onExitCode == null) {
            onExitCode = new ArrayList<String>();
        }
        return this.onExitCode;
    }

}
