/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
package com.sos.scheduler.model.objects;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import org.apache.log4j.Logger;
import org.joda.time.Interval;

import com.sos.scheduler.model.ISOSJsObjStartTimes;
import com.sos.scheduler.model.SchedulerObjectFactory;
import com.sos.scheduler.model.tools.RunTimeElements;

/**
* \class JSObjMonthdays 
* 
* \brief JSObjMonthdays - 
* 
* \details
*
* \section JSObjMonthdays.java_intro_sec Introduction
*
* \section JSObjMonthdays.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author oh
* @version $Id: JSObjMonthdays.java 20718 2013-07-18 18:16:10Z kb $
* \see reference
*
* Created on 09.02.2011 14:55:35
 */

/**
 * @author oh
 *
 */
public class JSObjMonthdays extends Monthdays implements ISOSJsObjStartTimes {

	@SuppressWarnings("unused")
	private final String		conClassName	= "JSObjMonthdays";
	@SuppressWarnings("unused")
	private static final Logger	logger			= Logger.getLogger(JSObjMonthdays.class);

	public JSObjMonthdays (SchedulerObjectFactory schedulerObjectFactory) {
		super();
		objFactory = schedulerObjectFactory;
	}

	@Override
	public RunTimeElements getRunTimeElements(Interval timeRange) {
		RunTimeElements result = new RunTimeElements(timeRange);
		result.putAll(getDtWeekdays(timeRange));
		result.putAll(getDtDays(timeRange));
//		Collections.sort(result, DateTimeComparator.getInstance());
		return result;
	}
	
	public List<JSObjMonthdaysDay> getJsObjMonthdaysDay() {
		List<JSObjMonthdaysDay> result = new ArrayList<JSObjMonthdaysDay>();
		Iterator<Object> it = getDayOrWeekday().iterator();
		while(it.hasNext()) {
			Object o = it.next();
			if (o instanceof Day) {
				Day d = (Day)o;
				JSObjMonthdaysDay day = new JSObjMonthdaysDay(objFactory);
				day.setObjectFieldsFrom(d);
				day.setHotFolderSrc(getHotFolderSrc());
				result.add(day);
			}
		}
		return result;
	}
	
	public List<JSObjWeekday> getJsObjWeekday() {
		List<JSObjWeekday> result = new ArrayList<JSObjWeekday>();
		Iterator<Object> it = getDayOrWeekday().iterator();
		while(it.hasNext()) {
			Object o = it.next();
			if (o instanceof Weekday) {
				Weekday w = (Weekday)o;
				JSObjWeekday weekday = new JSObjWeekday(objFactory);
				weekday.setObjectFieldsFrom(w);
				weekday.setHotFolderSrc(getHotFolderSrc());
				result.add(weekday);
			}
		}
		return result;
	}
	
	public RunTimeElements getDtWeekdays(Interval timeRange) {
		RunTimeElements result = new RunTimeElements(timeRange);
		for(JSObjWeekday weekday : getJsObjWeekday()) {
			result.putAll( weekday.getRunTimeElements(timeRange) );
		}
		return result;
	}
	
	public RunTimeElements getDtDays(Interval timeRange) {
		RunTimeElements result = new RunTimeElements(timeRange);
		for(JSObjMonthdaysDay day : getJsObjMonthdaysDay()) {
			result.putAll( day.getRunTimeElements(timeRange) );
		}
		return result;
	}
	
}
