/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.01.17 at 03:00:56 PM MEZ
//


package com.sos.scheduler.model.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="single_start" type="{}Time_of_day" />
 *       &lt;attribute name="begin" type="{}Time_of_day" />
 *       &lt;attribute name="end" type="{}Time_of_day" />
 *       &lt;attribute name="let_run" type="{}Yes_no" />
 *       &lt;attribute name="repeat" type="{}Duration" />
 *       &lt;attribute name="absolute_repeat" type="{}Duration" />
 *       &lt;attribute name="when_holiday" type="{}When_holiday" />
 *       &lt;attribute name="start_once" type="{}Yes_no" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "period")
public class Period extends JSObjBase {

    @XmlAttribute(name = "single_start")
    protected String singleStart;
    @XmlAttribute(name = "begin")
    protected String begin;
    @XmlAttribute(name = "end")
    protected String end;
    @XmlAttribute(name = "let_run")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String letRun;
    @XmlAttribute(name = "repeat")
    protected String repeat;
    @XmlAttribute(name = "absolute_repeat")
    protected String absoluteRepeat;
    @XmlAttribute(name = "when_holiday")
    protected WhenHoliday whenHoliday;
    @XmlAttribute(name = "start_once")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String startOnce;

    /**
     * Gets the value of the singleStart property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSingleStart() {
        return singleStart;
    }

    /**
     * Sets the value of the singleStart property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSingleStart(final String value) {
        singleStart = value;
    }

    /**
     * Gets the value of the begin property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBegin() {
        return begin;
    }

    /**
     * Sets the value of the begin property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBegin(final String value) {
        begin = value;
    }

    /**
     * Gets the value of the end property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEnd(final String value) {
        end = value;
    }

    /**
     * Gets the value of the letRun property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLetRun() {
        return letRun;
    }

    /**
     * Sets the value of the letRun property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLetRun(final String value) {
        letRun = value;
    }

    /**
     * Gets the value of the repeat property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRepeat() {
        return repeat;
    }

    /**
     * Sets the value of the repeat property.
     *
     * Should a job not already be running, then it will be started at the start of the operating period. After the job has ended, it will be restarted after the time specified, as far as allowed by the <run_time> attribute. This repeat interval can be specified in hh:mm, in hh:mm:ss or in seconds.

Cannot be combined with the single_start= attribute.

The job will not be repeated, if repeat="0" (the default value) is set.
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRepeat(final String value) {
        repeat = value;
    }

    /**
     * Gets the value of the absoluteRepeat property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAbsoluteRepeat() {
        return absoluteRepeat;
    }

    /**
     * Sets the value of the absoluteRepeat property.
     *
     *  Similar to repeat but allows the begin and end times to be specified independently of a Job Scheduler's operating period.

Starts a job, should it not already be running, at the beginning of a specified time period. Thereafter, the job will be restarted at regular intervals. The job starting times then result from the begin time plus a multiple of the absolute_repeat interval. This repeat interval can be specified in hh:mm, in hh:mm:ss or in seconds.

Cannot be combined with the single_start= attribute.
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAbsoluteRepeat(final String value) {
        absoluteRepeat = value;
    }

    /**
     * Gets the value of the whenHoliday property.
     *
     * @return
     *     possible object is
     *     {@link WhenHoliday }
     *
     */
    public WhenHoliday getWhenHoliday() {
        return whenHoliday;
    }

    /**
     * Sets the value of the whenHoliday property.
     *
     * @param value
     *     allowed object is
     *     {@link WhenHoliday }
     *
     */
    public void setWhenHoliday(final WhenHoliday value) {
        whenHoliday = value;
    }

    /**
     * Gets the value of the startOnce property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStartOnce() {
        return startOnce;
    }

    /**
     * Sets the value of the startOnce property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStartOnce(final String value) {
        startOnce = value;
    }

}
