/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
package com.sos.JSHelper.Exceptions;
import org.apache.log4j.Logger;

import com.sos.i18n.annotation.I18NResourceBundle;

/**
* \class JSNotImplementedException 
* 
* \brief JSNotImplementedException - 
* 
* \details
*
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author KB
* \version $Id$
* \see reference
*
* Created on 20.08.2011 11:53:15
 */

/**
 * @author KB
 * 
 * @Version $Id$
 */
@I18NResourceBundle(baseName = "com_sos_JSHelper_Messages", defaultLocale = "en")
public class JSNotImplementedException extends JobSchedulerException {

	private static final long	serialVersionUID	= 8821743868485352721L;
	@SuppressWarnings("unused")
	private final String		conClassName	= "JSNotImplementedException";
	@SuppressWarnings("unused")
	private static final String  conSVNVersion = "$Id$";
	@SuppressWarnings("unused")
	private static final Logger	logger					= Logger.getLogger(JSNotImplementedException.class);

	public JSNotImplementedException () {
        super("Function not implemented.");
	}

	/**
	 * \brief JSNotImplementedException
	 *
	 * \details
	 *
	 * @param pstrMessage
	 */
	public JSNotImplementedException(String pstrMessage) {
		super(pstrMessage);
		// TODO Auto-generated constructor stub
	}

	/**
	 * \brief JSNotImplementedException
	 *
	 * \details
	 *
	 * @param pstrMessage
	 * @param e
	 */
	public JSNotImplementedException(String pstrMessage, Exception e) {
		super(pstrMessage, e);
		// TODO Auto-generated constructor stub
	}
}
