/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
/** ---------------------------------------------------------------------------
 APL/Software GmbH - Berlin
##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
2007-07-06, sgx1190 (sgx1190)
-------------------------------------------------------------------------------
<docu type="smcw" version="1.0">
<project></project>
<name>MissingWritePermissionException</name>
<title>Exception für fehlende Schreibrechte (Ampeldateien)
</title>
<description>
<para>
Exception für fehlende Schreibrechte (Ampeldateien)
</para>
</description>
<params>
</params>
<keywords>
  <keyword>FTP</keyword>
  <keyword>Receive</keyword>
  <keyword>write permission</keyword>
</keywords>
<categories>
<category>Receive</category>
<category>FTP</category>
</categories>
<date>2007-07-06</date>
<copyright>(c) 06.07.2007 by sgx1190</copyright>
<author>sgx1190</author>
<changes>
 <change who='sgx1190' when='2007-07-06' id='created'>
   <what>
   <para>
   created
   </para>
   </what>
 </change>
</changes>
</docu>
---------------------------------------------------------------------------- */
package com.sos.JSHelper.Exceptions;

public class MissingWritePermissionException extends JobSchedulerException {

  /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

public MissingWritePermissionException() {
    this("Don't have write permissions to a file!");
  }

  public MissingWritePermissionException(String message) {
    super(message);
    this.Status(JobSchedulerException.PENDING);		    
    this.Category(CategoryFileHandling);
    
  }

}
