/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
package com.sos.jobnet.classes;


/**
* \class EdgeType 
* 
* \brief EdgeType - 
* 
* \details
*
* \section EdgeType.java_intro_sec Introduction
*
* \section EdgeType.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 21.09.2011
* \see reference
*
* Created on 21.09.2011 11:05:32
 */

public class EdgeType {
 
 
	@SuppressWarnings("unused")
	private final String	conClassName	= "EdgeType";
	public final String		conSVNVersion	= "$Id: EdgeType.java 16620 2012-02-28 11:08:57Z ur $";

	private String edgeType;
 	 

	public EdgeType() {
		//
	}
	
	public String getEdgeType()   {
			return edgeType;
	}

	
	public void setEdgeType(String edgeType_) throws Exception {
		EdgeTypeValues e = new EdgeTypeValues();
		if (e.isPredecessors(edgeType_) || e.isSuccessor(edgeType_)) {
			edgeType = edgeType_;
		}else {
		  throw new Exception (String.format("Edge Type %1 not found",edgeType_));
		}
	}
	
	public String successor(){
		return EdgeTypeValues.enuEdgeType.S.value();
	}
 
	public String predeccessors(){
		return EdgeTypeValues.enuEdgeType.P.value();
	}
 
	public void setEdgeTypeSuccessors()  {
		try {
			this.setEdgeType(EdgeTypeValues.enuEdgeType.S.value());
		}
		catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void setEdgeTypePredecessors() {
		try {
			this.setEdgeType(EdgeTypeValues.enuEdgeType.P.value());
		}
		catch (Exception e) {
			e.printStackTrace();
		}
	}
}
