/**
 * Copyright (C) 2014 BigLoupe http://bigloupe.github.io/SoS-JobScheduler/
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License
 */
/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
package com.sos.jobnet.classes;

import org.apache.log4j.Logger;

/**
* \class JobNetConstants 
* 
* \brief JobNetConstants - 
* 
* \details
*
* \section JobNetConstants.java_intro_sec Introduction
*
* \section JobNetConstants.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author oh
* @version $Id$
* \see reference
*
* Created on 28.02.2012 15:19:04
 */
public class JobNetConstants {
	@SuppressWarnings("unused")
	private final String		conClassName		= "JobNetConstants";
	@SuppressWarnings("unused")
	private static final String conSVNVersion 		= "$Id$";
	@SuppressWarnings("unused")
	private static final Logger	logger				= Logger.getLogger(JobNetConstants.class);
	public static final String	strBundleBaseName	= "com_sos_jobnet_messages";
	
	public static final String	JOBNET_D_0001		= "JOBNET_D_0001";		// %s: Parameter %s="%s"
	public static final String	JOBNET_D_0010		= "JOBNET_D_0010";		// %s: The current node is 2s
	public static final String	JOBNET_D_0011		= "JOBNET_D_0011";		// %s: %s status -> %s 
	public static final String	JOBNET_D_0020		= "JOBNET_D_0020";		// %s: The %s of the current node is skipped? %s
	public static final String	JOBNET_D_0021		= "JOBNET_D_0021";		// %s: The current node is bootstrap? %s
	public static final String	JOBNET_D_0022		= "JOBNET_D_0022";		// %s: The %s of the current node is on demand? %s
	
	public static final String	JOBNET_T_0001		= "JOBNET_T_0001";		// Yes
	public static final String	JOBNET_T_0002		= "JOBNET_T_0002";		// No
	public static final String	JOBNET_T_0010		= "JOBNET_T_0010";		// WAITER
	public static final String	JOBNET_T_0011		= "JOBNET_T_0011";		// RUNNER
	public static final String	JOBNET_T_0012		= "JOBNET_T_0012";		// DISPATCHER
	public static final String	JOBNET_T_0013		= "JOBNET_T_0013";		// NODE
	
	public static final String	JOBNETW_I_0010		= "JOBNETW_I_0010";		// %s: The predecessor %s has the status %s

//	public static final String UUID_PARAMETER_NAME = "uuid_jobnet_identifier";
//	public static final String JOB_NET_PARAMETER_NAME = "jobnet";
//	public static final String JOB_CHAIN_NAME = "JobChainName";
//	public static final String JOB_NET_ID_PARAMETER_NAME = "JobNetIdParameterName";
//	public static final String SCRIPT_TO_EXECUTE = "script_to_execute";
//	public static final String ORDER_NAME_PARAMETER_NAME = "jobnet_order_name";
//	public static final String HIBERNATE_CONFIG_PARAMETER_NAME = "hibernate_connection_config_file";
	public static final String NODETYPE_PARAMETER_NAME = "nodetype";

	// a parameter in scheduler.xml which contains the root folder of the scripts to use
	// if this parameter is set it can be used in the parameter script_to_execute, e.g.
	// <param name="script_to_execute" value="%SCRIPT_ROOT%/subfolder/script.sh" />
	public static final String SCRIPT_ROOT_GLOBAL_PARAMETER_NAME = "SCRIPT_ROOT";

	public static final String JOBNET_ID_DELIMITER = ".";
	public static final String JOBNET_STARTED_PREFIX = "jobnet_started_event" + JOBNET_ID_DELIMITER;
	public static final String JOBNET_ENDED_PREFIX = "jobnet_ended_event" + JOBNET_ID_DELIMITER;

	private JobNetConstants() {}
}
