/**
 * Copyright (C) 2014 BigLoupe http://bigloupe.github.io/SoS-JobScheduler/
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License
 */
/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
package com.sos.jobnet.classes;

import org.apache.log4j.Logger;
import org.eclipse.swt.SWT;

import org.eclipse.swt.graphics.Color;
 
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Table;
import com.sos.jobnet.db.JobNetCmdHistoryDBItem;
import com.sos.dialog.classes.SOSTableItem;
import com.sos.hibernate.classes.DbItem;
import com.sos.hibernate.interfaces.ISOSTableItem;

/**
* \class SosJobNetCmdHistoryTableItem 
* 
* \brief SosJobNetCmdHistoryTableItem - 
* 
* \details
*
* \section SosJobNetCmdHistoryTableItem.java_intro_sec Introduction
*
* \section SosJobNetCmdHistoryTableItem.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 14.12.2011
* \see reference
*
* Created on 14.12.2011 13:51:13
 */

public class SosJobNetCmdHistoryTableItem extends SOSTableItem implements ISOSTableItem {
    private JobNetCmdHistoryDBItem jobNetCmdHistoryDBItem = null;
    private String[]         textBuffer       = null;
    private static Logger    logger           = Logger.getLogger(SosJobNetCmdHistoryTableItem.class);

 

    public SosJobNetCmdHistoryTableItem(Table arg0, int arg1) {
        super(arg0, arg1);
     }

    protected void checkSubclass() {
        // Disable the check that prevents subclassing of SWT components
    }

    public DbItem getData() {
        return (JobNetCmdHistoryDBItem) super.getData();
    }

    public void setDBItem(DbItem d) {
        jobNetCmdHistoryDBItem = (JobNetCmdHistoryDBItem) d;
        this.setData(d);
    }

    public void setColor() {
        org.eclipse.swt.graphics.Color magenta = Display.getDefault().getSystemColor(SWT.COLOR_DARK_MAGENTA);
        org.eclipse.swt.graphics.Color red = Display.getDefault().getSystemColor(SWT.COLOR_RED);
        org.eclipse.swt.graphics.Color blue = Display.getDefault().getSystemColor(SWT.COLOR_BLUE);
        org.eclipse.swt.graphics.Color white = Display.getDefault().getSystemColor(SWT.COLOR_WHITE);
        org.eclipse.swt.graphics.Color gray = Display.getDefault().getSystemColor(SWT.COLOR_WIDGET_LIGHT_SHADOW);
        org.eclipse.swt.graphics.Color black = Display.getDefault().getSystemColor(SWT.COLOR_BLACK);
        org.eclipse.swt.graphics.Color yellow = Display.getDefault().getSystemColor(SWT.COLOR_YELLOW);
        org.eclipse.swt.graphics.Color darkRed = Display.getDefault().getSystemColor(SWT.COLOR_DARK_RED);
        org.eclipse.swt.graphics.Color green = Display.getDefault().getSystemColor(SWT.COLOR_GREEN);
        org.eclipse.swt.graphics.Color darkGreen = Display.getDefault().getSystemColor(SWT.COLOR_DARK_GREEN);
        org.eclipse.swt.graphics.Color darkYellow = Display.getDefault().getSystemColor(SWT.COLOR_DARK_YELLOW);
        org.eclipse.swt.graphics.Color darkBlue = Display.getDefault().getSystemColor(SWT.COLOR_DARK_BLUE);
        org.eclipse.swt.graphics.Color cyan = Display.getDefault().getSystemColor(SWT.COLOR_CYAN);
        org.eclipse.swt.graphics.Color darkCyan = Display.getDefault().getSystemColor(SWT.COLOR_DARK_CYAN);
        org.eclipse.swt.graphics.Color darkGray = Display.getDefault().getSystemColor(SWT.COLOR_DARK_GRAY);

        this.setBackground(white);
 

        colorSave();

    }

   

    public void setColumns() {
       
        JobNetCmdHistoryDBItem d = jobNetCmdHistoryDBItem;

        logger.debug("...creating tableItem: " + d.getHistoryId() );

        textBuffer = new String[] { " ", 
                d.getStartOption(), 
                d.getNodeType(), 
                d.getStartTimeFormated() 
                 };
        this.setText(textBuffer);
         
        
         
    }

    public String[] getTextBuffer() {
        return textBuffer;
    }

    @SuppressWarnings("unused")
    private final String conClassName = "SosJobNetCmdHistoryTableItem";

    @Override
    public Color getBackground() {
        return null;
    }

    @Override
    public Color getForeground() {
        return null;
    }

    @Override
    public Color[] getBackgroundColumn() {
        return colorsBackground;
    }

    @Override
    public Color[] getForegroundColumn() {
        return colorsForeground;
    }

}
