/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.08 at 02:48:08 PM MEZ 
//


package com.sos.scheduler.model.xmldoc;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sos.scheduler.model.xmldoc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sos.scheduler.model.xmldoc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Description.Configuration.Settings.Profile }
     * 
     */
    public Description.Configuration.Settings.Profile createDescriptionConfigurationSettingsProfile() {
        return new Description.Configuration.Settings.Profile();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link Script.Include }
     * 
     */
    public Script.Include createScriptInclude() {
        return new Script.Include();
    }

    /**
     * Create an instance of {@link Description.Configuration.Params }
     * 
     */
    public Description.Configuration.Params createDescriptionConfigurationParams() {
        return new Description.Configuration.Params();
    }

    /**
     * Create an instance of {@link Description.Releases.Release }
     * 
     */
    public Description.Releases.Release createDescriptionReleasesRelease() {
        return new Description.Releases.Release();
    }

    /**
     * Create an instance of {@link Description.Releases }
     * 
     */
    public Description.Releases createDescriptionReleases() {
        return new Description.Releases();
    }

    /**
     * Create an instance of {@link Description.Configuration.Payload.Params }
     * 
     */
    public Description.Configuration.Payload.Params createDescriptionConfigurationPayloadParams() {
        return new Description.Configuration.Payload.Params();
    }

    /**
     * Create an instance of {@link Description.Configuration.Settings.Profile.Section }
     * 
     */
    public Description.Configuration.Settings.Profile.Section createDescriptionConfigurationSettingsProfileSection() {
        return new Description.Configuration.Settings.Profile.Section();
    }

    /**
     * Create an instance of {@link Description.Job }
     * 
     */
    public Description.Job createDescriptionJob() {
        return new Description.Job();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Description.Releases.Release.Author }
     * 
     */
    public Description.Releases.Release.Author createDescriptionReleasesReleaseAuthor() {
        return new Description.Releases.Release.Author();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Description.Configuration.Settings.Connection.Application.Section }
     * 
     */
    public Description.Configuration.Settings.Connection.Application.Section createDescriptionConfigurationSettingsConnectionApplicationSection() {
        return new Description.Configuration.Settings.Connection.Application.Section();
    }

    /**
     * Create an instance of {@link Description.Configuration.Settings.Connection }
     * 
     */
    public Description.Configuration.Settings.Connection createDescriptionConfigurationSettingsConnection() {
        return new Description.Configuration.Settings.Connection();
    }

    /**
     * Create an instance of {@link Script }
     * 
     */
    public Script createScript() {
        return new Script();
    }

    /**
     * Create an instance of {@link Description.Resources }
     * 
     */
    public Description.Resources createDescriptionResources() {
        return new Description.Resources();
    }

    /**
     * Create an instance of {@link Description.Job.Monitor }
     * 
     */
    public Description.Job.Monitor createDescriptionJobMonitor() {
        return new Description.Job.Monitor();
    }

    /**
     * Create an instance of {@link Description.Job.Process }
     * 
     */
    public Description.Job.Process createDescriptionJobProcess() {
        return new Description.Job.Process();
    }

    /**
     * Create an instance of {@link Description.Configuration.Payload.Document }
     * 
     */
    public Description.Configuration.Payload.Document createDescriptionConfigurationPayloadDocument() {
        return new Description.Configuration.Payload.Document();
    }

    /**
     * Create an instance of {@link Description.Configuration }
     * 
     */
    public Description.Configuration createDescriptionConfiguration() {
        return new Description.Configuration();
    }

    /**
     * Create an instance of {@link Description.Configuration.Payload }
     * 
     */
    public Description.Configuration.Payload createDescriptionConfigurationPayload() {
        return new Description.Configuration.Payload();
    }

    /**
     * Create an instance of {@link Setting }
     * 
     */
    public Setting createSetting() {
        return new Setting();
    }

    /**
     * Create an instance of {@link Documentation }
     * 
     */
    public Documentation createDocumentation() {
        return new Documentation();
    }

    /**
     * Create an instance of {@link Description.Job.Process.Environment.Variable }
     * 
     */
    public Description.Job.Process.Environment.Variable createDescriptionJobProcessEnvironmentVariable() {
        return new Description.Job.Process.Environment.Variable();
    }

    /**
     * Create an instance of {@link Description.Configuration.Settings.Connection.Application }
     * 
     */
    public Description.Configuration.Settings.Connection.Application createDescriptionConfigurationSettingsConnectionApplication() {
        return new Description.Configuration.Settings.Connection.Application();
    }

    /**
     * Create an instance of {@link Description.Resources.Space }
     * 
     */
    public Description.Resources.Space createDescriptionResourcesSpace() {
        return new Description.Resources.Space();
    }

    /**
     * Create an instance of {@link Description.Resources.Memory }
     * 
     */
    public Description.Resources.Memory createDescriptionResourcesMemory() {
        return new Description.Resources.Memory();
    }

    /**
     * Create an instance of {@link Description.Job.Process.Environment }
     * 
     */
    public Description.Job.Process.Environment createDescriptionJobProcessEnvironment() {
        return new Description.Job.Process.Environment();
    }

    /**
     * Create an instance of {@link Changes }
     * 
     */
    public Changes createChanges() {
        return new Changes();
    }

    /**
     * Create an instance of {@link Description.Resources.File }
     * 
     */
    public Description.Resources.File createDescriptionResourcesFile() {
        return new Description.Resources.File();
    }

    /**
     * Create an instance of {@link Description.Resources.Database.Resource }
     * 
     */
    public Description.Resources.Database.Resource createDescriptionResourcesDatabaseResource() {
        return new Description.Resources.Database.Resource();
    }

    /**
     * Create an instance of {@link Description.Resources.Database }
     * 
     */
    public Description.Resources.Database createDescriptionResourcesDatabase() {
        return new Description.Resources.Database();
    }

    /**
     * Create an instance of {@link Description.Configuration.Settings }
     * 
     */
    public Description.Configuration.Settings createDescriptionConfigurationSettings() {
        return new Description.Configuration.Settings();
    }

}
