/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.20 at 05:15:15 PM MEZ 
//


package com.sos.scheduler.model.answers;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.sos.JSHelper.Basics.JSToolBox;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sos.scheduler.model.answers package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory extends JSToolBox {

    private final static QName _Logfile_QNAME = new QName("", "logfile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sos.scheduler.model.answers
     * 
     */
    public ObjectFactory() {
    }

    public ObjectFactory(final String pstrI18NFileName) {
    	super(pstrI18NFileName);
    }

    /**
     * Create an instance of {@link OrderQueue }
     * 
     */
    public OrderQueue createOrderQueue() {
        return new OrderQueue();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link FileBased }
     * 
     */
    public FileBased createFileBased() {
        return new FileBased();
    }

    /**
     * Create an instance of {@link Includes }
     * 
     */
    public Includes createIncludes() {
        return new Includes();
    }

    /**
     * Create an instance of {@link Include }
     * 
     */
    public Include createInclude() {
        return new Include();
    }

    /**
     * Create an instance of {@link Requisites }
     * 
     */
    public Requisites createRequisites() {
        return new Requisites();
    }

    /**
     * Create an instance of {@link Requisite }
     * 
     */
    public Requisite createRequisite() {
        return new Requisite();
    }

    /**
     * Create an instance of {@link ProcessClasses }
     * 
     */
    public ProcessClasses createProcessClasses() {
        return new ProcessClasses();
    }

    /**
     * Create an instance of {@link ProcessClass }
     * 
     */
    public ProcessClass createProcessClass() {
        return new ProcessClass();
    }

    /**
     * Create an instance of {@link HistoryEntry }
     * 
     */
    public HistoryEntry createHistoryEntry() {
        return new HistoryEntry();
    }

    /**
     * Create an instance of {@link Jobs }
     * 
     */
    public Jobs createJobs() {
        return new Jobs();
    }

    /**
     * Create an instance of {@link Job }
     * 
     */
    public Job createJob() {
        return new Job();
    }

    /**
     * Create an instance of {@link LockRequestor }
     * 
     */
    public LockRequestor createLockRequestor() {
        return new LockRequestor();
    }

    /**
     * Create an instance of {@link LockUse }
     * 
     */
    public LockUse createLockUse() {
        return new LockUse();
    }

    /**
     * Create an instance of {@link Tasks }
     * 
     */
    public Tasks createTasks() {
        return new Tasks();
    }

    /**
     * Create an instance of {@link QueuedTasks }
     * 
     */
    public QueuedTasks createQueuedTasks() {
        return new QueuedTasks();
    }

    /**
     * Create an instance of {@link ERROR }
     * 
     */
    public ERROR createERROR() {
        return new ERROR();
    }

    /**
     * Create an instance of {@link Log }
     * 
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link Folder }
     * 
     */
    public Folder createFolder() {
        return new Folder();
    }

    /**
     * Create an instance of {@link Folders }
     * 
     */
    public Folders createFolders() {
        return new Folders();
    }

    /**
     * Create an instance of {@link JobChains }
     * 
     */
    public JobChains createJobChains() {
        return new JobChains();
    }

    /**
     * Create an instance of {@link JobChain }
     * 
     */
    public JobChain createJobChain() {
        return new JobChain();
    }

    /**
     * Create an instance of {@link FileOrderSource }
     * 
     */
    public FileOrderSource createFileOrderSource() {
        return new FileOrderSource();
    }

    /**
     * Create an instance of {@link JobChainNode }
     * 
     */
    public JobChainNode createJobChainNode() {
        return new JobChainNode();
    }

    /**
     * Create an instance of {@link FileOrderSink }
     * 
     */
    public FileOrderSink createFileOrderSink() {
        return new FileOrderSink();
    }

    /**
     * Create an instance of {@link Locks }
     * 
     */
    public Locks createLocks() {
        return new Locks();
    }

    /**
     * Create an instance of {@link Lock }
     * 
     */
    public Lock createLock() {
        return new Lock();
    }

    /**
     * Create an instance of {@link Orders }
     * 
     */
    public Orders createOrders() {
        return new Orders();
    }

    /**
     * Create an instance of {@link Subprocesses }
     * 
     */
    public Subprocesses createSubprocesses() {
        return new Subprocesses();
    }

    /**
     * Create an instance of {@link RemoteSchedulers }
     * 
     */
    public RemoteSchedulers createRemoteSchedulers() {
        return new RemoteSchedulers();
    }

    /**
     * Create an instance of {@link HttpServer }
     * 
     */
    public HttpServer createHttpServer() {
        return new HttpServer();
    }

    /**
     * Create an instance of {@link Connections }
     * 
     */
    public Connections createConnections() {
        return new Connections();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

    /**
     * Create an instance of {@link Peer }
     * 
     */
    public Peer createPeer() {
        return new Peer();
    }

    /**
     * Create an instance of {@link Operation }
     * 
     */
    public Operation createOperation() {
        return new Operation();
    }

    /**
     * Create an instance of {@link XmlOperation }
     * 
     */
    public XmlOperation createXmlOperation() {
        return new XmlOperation();
    }

    /**
     * Create an instance of {@link Ok }
     * 
     */
    public Ok createOk() {
        return new Ok();
    }

    /**
     * Create an instance of {@link Task }
     * 
     */
    public Task createTask() {
        return new Task();
    }

    /**
     * Create an instance of {@link Calendar }
     * 
     */
    public Calendar createCalendar() {
        return new Calendar();
    }

    /**
     * Create an instance of {@link At }
     * 
     */
    public At createAt() {
        return new At();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link Answer }
     * 
     */
    public Answer createAnswer() {
        return new Answer();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link Spooler }
     * 
     */
    public Spooler createSpooler() {
        return new Spooler();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "logfile")
    public JAXBElement<String> createLogfile(String value) {
        return new JAXBElement<String>(_Logfile_QNAME, String.class, null, value);
    }

}
