/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
package com.sos.JSHelper.Options;

/**
* \class JSOptionPropertyFolderName
*
* \brief JSOptionPropertyFolderName -
*
* \details
*
* \section JSOptionPropertyFolderName.java_intro_sec Introduction
*
* \section JSOptionPropertyFolderName.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author eqbfd
* @version $Id: JSOptionPropertyFolderName.java 19850 2013-04-08 08:44:29Z kb $29.01.2009
* \see reference
*
* Created on 29.01.2009 20:00:12
 */

/**
 * @author eqbfd
 *
 */
public class JSOptionPropertyFolderName extends SOSOptionFolderName {

	private static final long	serialVersionUID	= -5962741104646578748L;
	@SuppressWarnings("unused")
	private final String	conClassName	= "JSOptionPropertyFolderName";

	/**
	 * \brief JSOptionPropertyFolderName
	 *
	 * \details
	 *
	 * @param pPobjParent
	 * @param pPstrKey
	 * @param pPstrDescription
	 * @param pPstrValue
	 * @param pPstrDefaultValue
	 * @param pPflgIsMandatory
	 */
	public JSOptionPropertyFolderName(final JSOptionsClass pPobjParent, final String pPstrKey, final String pPstrDescription, final String pPstrValue, final String pPstrDefaultValue,
			final boolean pPflgIsMandatory) {
		super(pPobjParent, pPstrKey, "Java-Property user.dir", pPstrValue, pPstrDefaultValue, pPflgIsMandatory);

		//		strValue = this.Value();
	}

	/**
	 *
	 * \brief Value - setzt die Property UserDir
	 *
	 * \details
	 *
	 * \return
	 *
	 * @param pstrFolderName
	 * @throws Exception
	 */
	@Override
	public void Value(String pstrFolderName) {

		@SuppressWarnings("unused")
		final String conMethodName = conClassName + "::Value";
		// prüfen, ob es den Folder gibt ...
		pstrFolderName = objParentClass.CheckIsFileWritable(pstrFolderName, conMethodName);
		super.Value(pstrFolderName);
		if (isNotEmpty(strValue)) {
			System.setProperty("user.dir", strValue);
		}

		//		return void;
	} // public void Value

	@Override
	public String Value() {

		@SuppressWarnings("unused")
		final String conMethodName = conClassName + "::Value";

		String strT = System.getProperty("user.dir");

		return strT;
	} // public String Value

}
