/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
package com.sos.jobnet.interfaces;

import com.sos.jobnet.classes.NodeStatus;
import com.sos.jobnet.db.EventsDBItem;
import com.sos.jobnet.dispatcher.JobNetDispatcher;
import com.sos.jobnet.options.JobNetOptions;
import com.sos.jobnet.waiter.JobNetWaiter;
import org.apache.log4j.Level;

/**
* \class IJobNetCallback 
* 
* \brief IJobNetCallback - 
* 
* \details
*
* \section IJobNetCallback.java_intro_sec Introduction
*
* \section IJobNetCallback.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author oh
* @version $Id: IJobNetCallback.java 21040 2013-09-09 16:51:14Z ss $
* \see reference
*
* Created on 27.02.2012 15:22:24
 */
public interface IJobNetCallback {
	public abstract int getExitCode();
	public abstract void setNextState();
	public abstract void log(Level level, String stateText, Throwable error);
	public abstract void log(Level level, String stateText);
	public abstract void logStatus(IPlanItem record, NodeStatus oldStatus);
	public abstract void logContextStatus(String context, NodeStatus fromStatus, NodeStatus toStatus);
	public abstract void setStateText(String stateText);
 	public abstract void startNode(IPlanItem planItem, JobNetOptions options);
 	public abstract void skipRunner();
	public abstract EventsDBItem createEventRecord(String forEventClass, String forEventId);
	public abstract void jobnetStarted(JobNetWaiter waiter);
	public abstract void jobnetEnded(JobNetDispatcher dispatcher);
}
