/**
 * Copyright (C) 2014 BigLoupe http://bigloupe.github.io/SoS-JobScheduler/
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License
 */
/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 11:06:03 AM MESZ 
//


package sos.scheduler.InstallationService.batchInstallationModel.installationFile;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}com.izforge.izpack.panels.UserInputPanel"/>
 *         &lt;element ref="{}com.izforge.izpack.panels.HTMLLicencePanel"/>
 *         &lt;element ref="{}com.izforge.izpack.panels.TargetPanel"/>
 *         &lt;element ref="{}com.izforge.izpack.panels.UserPathPanel"/>
 *         &lt;element ref="{}com.izforge.izpack.panels.FinishPanel"/>
 *         &lt;element ref="{}com.izforge.izpack.panels.InstallPanel"/>
 *         &lt;element ref="{}com.izforge.izpack.panels.ProcessPanel"/>
 *       &lt;/choice>
 *       &lt;attribute name="langpack" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "comIzforgeIzpackPanelsUserInputPanelOrComIzforgeIzpackPanelsHTMLLicencePanelOrComIzforgeIzpackPanelsTargetPanel"
})
@XmlRootElement(name = "AutomatedInstallation")
public class AutomatedInstallation {

    @XmlElements({
        @XmlElement(name = "com.izforge.izpack.panels.ProcessPanel", type = ComIzforgeIzpackPanelsProcessPanel.class),
        @XmlElement(name = "com.izforge.izpack.panels.InstallPanel", type = ComIzforgeIzpackPanelsInstallPanel.class),
        @XmlElement(name = "com.izforge.izpack.panels.UserPathPanel", type = ComIzforgeIzpackPanelsUserPathPanel.class),
        @XmlElement(name = "com.izforge.izpack.panels.HTMLLicencePanel", type = ComIzforgeIzpackPanelsHTMLLicencePanel.class),
        @XmlElement(name = "com.izforge.izpack.panels.FinishPanel", type = ComIzforgeIzpackPanelsFinishPanel.class),
        @XmlElement(name = "com.izforge.izpack.panels.TargetPanel", type = ComIzforgeIzpackPanelsTargetPanel.class),
        @XmlElement(name = "com.izforge.izpack.panels.UserInputPanel", type = ComIzforgeIzpackPanelsUserInputPanel.class)
    })
    protected List<Object> comIzforgeIzpackPanelsUserInputPanelOrComIzforgeIzpackPanelsHTMLLicencePanelOrComIzforgeIzpackPanelsTargetPanel;
    @XmlAttribute(required = true)
    protected String langpack;

    /**
     * Gets the value of the comIzforgeIzpackPanelsUserInputPanelOrComIzforgeIzpackPanelsHTMLLicencePanelOrComIzforgeIzpackPanelsTargetPanel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comIzforgeIzpackPanelsUserInputPanelOrComIzforgeIzpackPanelsHTMLLicencePanelOrComIzforgeIzpackPanelsTargetPanel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComIzforgeIzpackPanelsUserInputPanelOrComIzforgeIzpackPanelsHTMLLicencePanelOrComIzforgeIzpackPanelsTargetPanel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComIzforgeIzpackPanelsProcessPanel }
     * {@link ComIzforgeIzpackPanelsInstallPanel }
     * {@link ComIzforgeIzpackPanelsUserPathPanel }
     * {@link ComIzforgeIzpackPanelsHTMLLicencePanel }
     * {@link ComIzforgeIzpackPanelsFinishPanel }
     * {@link ComIzforgeIzpackPanelsTargetPanel }
     * {@link ComIzforgeIzpackPanelsUserInputPanel }
     * 
     * 
     */
    public List<Object> getComIzforgeIzpackPanelsUserInputPanelOrComIzforgeIzpackPanelsHTMLLicencePanelOrComIzforgeIzpackPanelsTargetPanel() {
        if (comIzforgeIzpackPanelsUserInputPanelOrComIzforgeIzpackPanelsHTMLLicencePanelOrComIzforgeIzpackPanelsTargetPanel == null) {
            comIzforgeIzpackPanelsUserInputPanelOrComIzforgeIzpackPanelsHTMLLicencePanelOrComIzforgeIzpackPanelsTargetPanel = new ArrayList<Object>();
        }
        return this.comIzforgeIzpackPanelsUserInputPanelOrComIzforgeIzpackPanelsHTMLLicencePanelOrComIzforgeIzpackPanelsTargetPanel;
    }

    /**
     * Gets the value of the langpack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLangpack() {
        return langpack;
    }

    /**
     * Sets the value of the langpack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLangpack(String value) {
        this.langpack = value;
    }

}
