/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 11:06:03 AM MESZ 
//


package sos.scheduler.InstallationService.batchInstallationModel.installationFile;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sos.scheduler.InstallationService.batchInstallationModel.installationFile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UserPathPanelElement_QNAME = new QName("", "UserPathPanelElement");
    private final static QName _Installpath_QNAME = new QName("", "installpath");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sos.scheduler.InstallationService.batchInstallationModel.installationFile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link AutomatedInstallation }
     * 
     */
    public AutomatedInstallation createAutomatedInstallation() {
        return new AutomatedInstallation();
    }

    /**
     * Create an instance of {@link ComIzforgeIzpackPanelsFinishPanel }
     * 
     */
    public ComIzforgeIzpackPanelsFinishPanel createComIzforgeIzpackPanelsFinishPanel() {
        return new ComIzforgeIzpackPanelsFinishPanel();
    }

    /**
     * Create an instance of {@link ComIzforgeIzpackPanelsUserInputPanel }
     * 
     */
    public ComIzforgeIzpackPanelsUserInputPanel createComIzforgeIzpackPanelsUserInputPanel() {
        return new ComIzforgeIzpackPanelsUserInputPanel();
    }

    /**
     * Create an instance of {@link UserInput }
     * 
     */
    public UserInput createUserInput() {
        return new UserInput();
    }

    /**
     * Create an instance of {@link ComIzforgeIzpackPanelsHTMLLicencePanel }
     * 
     */
    public ComIzforgeIzpackPanelsHTMLLicencePanel createComIzforgeIzpackPanelsHTMLLicencePanel() {
        return new ComIzforgeIzpackPanelsHTMLLicencePanel();
    }

    /**
     * Create an instance of {@link ComIzforgeIzpackPanelsUserPathPanel }
     * 
     */
    public ComIzforgeIzpackPanelsUserPathPanel createComIzforgeIzpackPanelsUserPathPanel() {
        return new ComIzforgeIzpackPanelsUserPathPanel();
    }

    /**
     * Create an instance of {@link ComIzforgeIzpackPanelsProcessPanel }
     * 
     */
    public ComIzforgeIzpackPanelsProcessPanel createComIzforgeIzpackPanelsProcessPanel() {
        return new ComIzforgeIzpackPanelsProcessPanel();
    }

    /**
     * Create an instance of {@link ComIzforgeIzpackPanelsInstallPanel }
     * 
     */
    public ComIzforgeIzpackPanelsInstallPanel createComIzforgeIzpackPanelsInstallPanel() {
        return new ComIzforgeIzpackPanelsInstallPanel();
    }

    /**
     * Create an instance of {@link ComIzforgeIzpackPanelsTargetPanel }
     * 
     */
    public ComIzforgeIzpackPanelsTargetPanel createComIzforgeIzpackPanelsTargetPanel() {
        return new ComIzforgeIzpackPanelsTargetPanel();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserPathPanelElement")
    public JAXBElement<String> createUserPathPanelElement(String value) {
        return new JAXBElement<String>(_UserPathPanelElement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "installpath")
    public JAXBElement<String> createInstallpath(String value) {
        return new JAXBElement<String>(_Installpath_QNAME, String.class, null, value);
    }

}
