/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
package com.sos.scheduler.model.commands;

import org.apache.log4j.Logger;

import com.sos.scheduler.model.SchedulerObjectFactory;

/**
* \class JSCmdJobChainModify 
* 
* \brief JSCmdJobChainModify - 
* 
* \details
*
* \section JSCmdJobChainModify.java_intro_sec Introduction
*
* \section JSCmdJobChainModify.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author oh
* @version $Id: JSCmdJobChainModify.java 20718 2013-07-18 18:16:10Z kb $
* \see reference
*
* Created on 08.02.2011 14:28:21
 */

/**
 * @author oh
 *
 */
public class JSCmdJobChainModify extends JobChainModify {

	private final String		conClassName	= "JSCmdJobChainModify";
	@SuppressWarnings("unused")
	private static final Logger	logger			= Logger.getLogger(JSCmdJobChainModify.class);
	
	public static enum enu4State {
    	STOPPED, RUNNING

		/**/;
		public String Text() {
			String strT = this.name().toLowerCase();
			return strT;
		}
	}

	public JSCmdJobChainModify (SchedulerObjectFactory schedulerObjectFactory) {
		super();
		objFactory = schedulerObjectFactory;
	}
	
	/**
	 * 
	 * \brief setState
	 * 
	 * \details
	 *
	 * @param penuT
	 */
	public void setState(enu4State penuT) {
	
		@SuppressWarnings("unused")
		final String	conMethodName	= conClassName + "::setState";
	
		super.setState(penuT.Text()); 
	
	} // private void setState
}
