/**
 * Copyright (C) 2014 BigLoupe http://bigloupe.github.io/SoS-JobScheduler/
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License
 */
/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
package com.sos.hibernate.classes;

import org.eclipse.swt.graphics.Color;

import com.sos.hibernate.interfaces.ISOSTableItem;

/**
* \class SosSortTableItem 
* 
* \brief SosSortTableItem - 
* 
* \details
* 
* \section SosSortTableItem.java_intro_sec Introduction
*
* \section SosSortTableItem.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 20.12.2011
* \see reference
*
* Created on 20.12.2011 13:43:21
 */

public class SosSortTableItem {

	@SuppressWarnings("unused")
	private final String	conClassName	= "SosSortTableItem";
	public String[] textBuffer;
 	public DbItem data;
    public Color background;
    public Color foreground;
    public Color[] backgroundColumn;
    public Color[] foregroundColumn;
 		


 	public SosSortTableItem() {
 
	}
 	

 	public SosSortTableItem(ISOSTableItem tableItem) {
		this.setTextBuffer(tableItem.getTextBuffer());
        this.setData((DbItem)tableItem.getData());
        this.setBackground(tableItem.getBackground());
        this.setForeground(tableItem.getForeground());
        
        this.setBackgroundColumn(tableItem.getBackgroundColumn());
        this.setForegroundColumn(tableItem.getForegroundColumn());
	}

	public String[] getTextBuffer() {
		return textBuffer;
	}

	public void setTextBuffer(String[] textBuffer) {
		this.textBuffer = textBuffer;
	}

	public Color getBackground() {
		return background;
	}

	public void setBackground(Color background) {
		this.background = background;
	}

	public DbItem getData() {
		return data;
	}

	public void setData(DbItem data) {
		this.data = data;
	}

	public Color getForeground() {
		return foreground;
	}

	public void setForeground(Color foreground) {
		this.foreground = foreground;
	}


    public Color[] getBackgroundColumn() {
        return backgroundColumn;
    }


    public void setBackgroundColumn(Color[] backgroundColumn) {
        this.backgroundColumn = backgroundColumn;
    }


    public Color[] getForegroundColumn() {
        return foregroundColumn;
    }


    public void setForegroundColumn(Color[] foregroundColumn) {
        this.foregroundColumn = foregroundColumn;
    }
}
