/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
package org.jobscheduler.dashboard.util;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.zip.GZIPInputStream;

/**
* \class SOSStreamUnzip 
* 
* \brief SOSStreamUnzip - 
* 
* \details
*
* \section SOSStreamUnzip.java_intro_sec Introduction
*
* \section SOSStreamUnzip.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 20.12.2011
* \see reference
*
* Created on 20.12.2011 10:28:32
 */

public class SOSStreamUnzip {

	@SuppressWarnings("unused")
	private final String	conClassName	= "SOSStreamUnzip";
    private byte[] source;
    private int bufferSize=8192;
    
	public SOSStreamUnzip(byte[] source_) {
		source = source_;
	}
	
	 public byte[] unzip( ) throws IOException {
		  InputStream  is = null; 
		  OutputStream os = null; 

		  is = new GZIPInputStream( new ByteArrayInputStream(source) ); 
		      os  = new ByteArrayOutputStream (); 
		      
		      byte[] buffer = new byte[ bufferSize ]; 
		 
		      for ( int length; (length = is.read(buffer)) >= 0; ) 
		        os.write( buffer, 0, length ); 
		   
		      if ( os != null ) try { os.close(); } catch ( IOException e ) { } 
		      if ( is != null ) try { is.close(); } catch ( IOException e ) { }
		      return ((ByteArrayOutputStream) os).toByteArray();
		    
	  }

	public String unzip2String( ) throws IOException {
		return new String(unzip());
	}
	
	public void setBufferSize(int bufferSize) {
		this.bufferSize = bufferSize;
	}   
}
