/**
 * Copyright (C) 2014 BigLoupe http://bigloupe.github.io/SoS-JobScheduler/
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License
 */
/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.21 at 08:04:29 PM CEST 
//


package com.sos.DataExchange.jaxb.configuration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sos.jade.jaxb.configuration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Value_QNAME = new QName("http://www.sos-berlin.com/schema/jade_configuration_v1.0", "value");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sos.jade.jaxb.configuration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JADEParam }
     * 
     */
    public JADEParam createJADEParam() {
        return new JADEParam();
    }

    /**
     * Create an instance of {@link ValidityElement }
     * 
     */
    public ValidityElement createValidityElement() {
        return new ValidityElement();
    }

    /**
     * Create an instance of {@link Include }
     * 
     */
    public Include createInclude() {
        return new Include();
    }

    /**
     * Create an instance of {@link JADEParamValues }
     * 
     */
    public JADEParamValues createJADEParamValues() {
        return new JADEParamValues();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link MergeElement }
     * 
     */
    public MergeElement createMergeElement() {
        return new MergeElement();
    }

    /**
     * Create an instance of {@link JADEParams }
     * 
     */
    public JADEParams createJADEParams() {
        return new JADEParams();
    }

    /**
     * Create an instance of {@link JADEProfileIncludes }
     * 
     */
    public JADEProfileIncludes createJADEProfileIncludes() {
        return new JADEProfileIncludes();
    }

    /**
     * Create an instance of {@link TitleElement }
     * 
     */
    public TitleElement createTitleElement() {
        return new TitleElement();
    }

    /**
     * Create an instance of {@link DescriptionElement }
     * 
     */
    public DescriptionElement createDescriptionElement() {
        return new DescriptionElement();
    }

    /**
     * Create an instance of {@link JADEDocumentation }
     * 
     */
    public JADEDocumentation createJADEDocumentation() {
        return new JADEDocumentation();
    }

    /**
     * Create an instance of {@link JADEProfiles }
     * 
     */
    public JADEProfiles createJADEProfiles() {
        return new JADEProfiles();
    }

    /**
     * Create an instance of {@link JADEProfile }
     * 
     */
    public JADEProfile createJADEProfile() {
        return new JADEProfile();
    }

    /**
     * Create an instance of {@link ConfigurationElement }
     * 
     */
    public ConfigurationElement createConfigurationElement() {
        return new ConfigurationElement();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Value }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sos-berlin.com/schema/jade_configuration_v1.0", name = "value")
    public JAXBElement<Value> createValue(final Value value) {
        return new JAXBElement<Value>(_Value_QNAME, Value.class, null, value);
    }

}
