/**
 * Copyright (C) 2014 BigLoupe http://bigloupe.github.io/SoS-JobScheduler/
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License
 */
/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
package com.sos.jobnet.db;

import com.sos.hibernate.classes.DbItem;
import com.sos.hibernate.classes.SOSHibernateFilter;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
 

 
/**
* \class SchedulerJobNetFilter 
* 
* \brief SchedulerJobNetFilter - 
* 
* \details
*
* \section SchedulerJobNetFilter.java_intro_sec Introduction
*
* \section SchedulerJobNetFilter.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 13.08.2013
* \see reference
*
* Created on 13.08.2013 13:53:37
 */

public class JobNetHistoryFilter extends SOSHibernateFilter implements com.sos.hibernate.interfaces.ISOSHibernateFilter {
//public class SchedulerJobNetFilter extends SOSHibernateFilter implements com.sos.hibernate.interfaces.ISOSHibernateFilter {


	@SuppressWarnings("unused")
	private final String	conClassName	= "SchedulerJobNetFilter";
	public  final String	conSVNVersion	= "$Id: SchedulerJobNetFilter.java 20187 2013-05-17 14:48:22Z ss $";
	private String dateFormat         = "yyyy-MM-dd HH:mm:ss";

	private Long historyId;
    private String schedulerId="";
    private Long netId;
	private String uuid;
	private Date startTime;
	private Date endTime;
	private Date startTimeFrom;
	private Date startTimeTo;
    private Integer status;
    private Integer exitCode;
    private String jobnetId;
    private String searchField;

 
	public void setStartTimeFrom(Date dateTime) {
		this.startTimeFrom = dateTime;
	}

	public void setStartTimeFrom(String startTimeFrom) throws ParseException {
	    if (startTimeFrom.equals("")) {
            this.startTimeFrom = null;
        }
        else {
            SimpleDateFormat formatter = new SimpleDateFormat(dateFormat);
            Date d = formatter.parse(startTimeFrom);
            setStartTimeFrom(d);
        }
	}

	public void setStartTimeFrom(String startTimeFrom, String dateFormat) throws ParseException {
		this.dateFormat = dateFormat;
		setStartTimeFrom(startTimeFrom);
		}
		 
	public void setStartTimeTo(String startTimeTo, String dateFormat) throws ParseException {
		this.dateFormat = dateFormat;
		setStartTimeTo(startTimeTo);
		}


	public void setStartTimeTo(Date startTimeTo) {
		this.startTimeTo  = startTimeTo;
	}

	public void setStartTimeTo(String startTimeTo) throws ParseException {
        if (startTimeTo.equals("")) {
            this.startTimeTo = null;
        }
        else {
            SimpleDateFormat formatter = new SimpleDateFormat(dateFormat);
            Date d = formatter.parse(startTimeTo);
            setStartTimeTo(d);
        }
		}

 
	@Override
	public String getTitle() {
 		return "";
	}

	@Override
	public boolean isFiltered(DbItem h) {
		return false;
 	}

    public String getDateFormat() {
        return dateFormat;
    }

    public void setDateFormat(String dateFormat) {
        this.dateFormat = dateFormat;
    }

    public Long getHistoryId() {
        return historyId;
    }

    public void setHistoryId(Long historyId) {
        this.historyId = historyId;
    }

    public String getSchedulerId() {
        return schedulerId;
    }

    public void setSchedulerId(String schedulerId) {
        this.schedulerId = schedulerId;
    }

    public Long getNetId() {
        return netId;
    }

    public void setNetId(long netId) {
        this.netId = netId;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getExitCode() {
        return exitCode;
    }

    public void setExitCode(Integer exitCode) {
        this.exitCode = exitCode;
    }

    public String getJobnetId() {
        return jobnetId;
    }

    public void setJobnetId(String jobnetId) {
        this.jobnetId = jobnetId;
    }

    public Date getStartTimeFrom() {
        return startTimeFrom;
    }

    public Date getStartTimeTo() {
        return startTimeTo;
    }

    public String getSearchField() {
        return searchField;
    }

    public void setSearchField(String searchField) {
        this.searchField = searchField;
    }


 
	 
	
	
}
