/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
package com.sos.jobnet.db;

/**
* \class JobnetNodesDBItem 
* 
* \brief JobnetNodesDBItem - 
* 
* \details
*
* \section JobnetNodesDBItem.java_intro_sec Introduction
*
* \section JobnetNodesDBItem.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 23.09.2011
* \see reference
*
* Created on 23.09.2011 15:08:05
 */

 
 import java.util.Date;
 

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;

import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.sos.hibernate.classes.DbItem;


@Entity
@Table(name="SCHEDULER_JOB_NET_CMD_HISTORY")
		
public class JobNetCmdHistoryDBItem  extends DbItem  {
	
	@SuppressWarnings("unused")

     private final String	conClassName	= "JobNetCmdHistoryDBItem";
	 public  final String	conSVNVersion	= "$Id: JobNetNodeDBItem.java 17391 2012-06-21 13:41:13Z ur $";

     private Long cmdHistoryId;
	 private Long historyId; 
     private String startOption;
     private String nodeType;
     private Date startTime;
     private Date created;
     private String createdBy;
     private JobNetHistoryDBItem jobNetHistoryDBItem;

      
 	public JobNetCmdHistoryDBItem() {
 	   super();
 	}
	
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="CMD_HISTORY_ID")
    public Long getCmdHistoryId() {
		return cmdHistoryId;
	}

	@Column(name="CMD_HISTORY_ID")
    public void setCmdHistoryId(Long cmdHistoryId) {
		this.cmdHistoryId = cmdHistoryId;
	}
 
	
	 @ManyToOne (optional=true)
	    @NotFound( action = NotFoundAction.IGNORE )
	    @JoinColumn (name="`HISTORY_ID`",  insertable = false, updatable = false)
	    public JobNetHistoryDBItem getjobNetHistoryDBItem() {
	        return jobNetHistoryDBItem;
	    }
	    public void setJobNetHistoryDBItem(JobNetHistoryDBItem jobNetHistoryDBItem)  {
	       this.jobNetHistoryDBItem = jobNetHistoryDBItem; 
	    }

	   
	
    @Column(name="HISTORY_ID")
    public Long getHistoryId() {
        return historyId;
    }

    @Column(name="HISTORY_ID")
    public void setHistoryId(Long historyId) {
        this.historyId = historyId;
    }
   
    @Column(name="START_OPTION",nullable=false)
	public void setStartOption(String startOption) {
		this.startOption = startOption;
	}
    
    @Column(name="START_OPTION",nullable=false)
	public String getStartOption() {
		return startOption;
	}
    

    @Column(name="NODE_TYPE",nullable=false)
	public void setNodeType(String nodeType) {
		this.nodeType = nodeType;
	}
 
    @Column(name="NODE_TYPE",nullable=false)
	public String getNodeType() {
		return nodeType;
	} 
    
    
    @Temporal (TemporalType.TIMESTAMP)
    @Column(name="CREATED",nullable=true)
    public void setCreated(Date created) {
        this.created = created;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED", nullable = true)
    public Date getCreated() {
        return created;
    }  
    
    @Column(name="CREATED_BY",nullable=true)
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
 
    @Column(name="CREATED_BY",nullable=true)
    public String getCreatedBy() {
        return createdBy;
    }
    
    @Temporal (TemporalType.TIMESTAMP)
    @Column(name="START_TIME",nullable=true)
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "START_TIME", nullable = true)
    public Date getStartTime() {
        return startTime;
    }
    
    @Transient 
    public String getStartTimeFormated(){
        return getDateFormatted(this.startTime);
    }
    
   
  
}
