/**
 * Copyright (C) 2014 BigLoupe http://bigloupe.github.io/SoS-JobScheduler/
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License
 */
/********************************************************* begin of preamble
**
** Copyright (C) 2003-2012 Software- und Organisations-Service GmbH. 
** All rights reserved.
**
** This file may be used under the terms of either the 
**
**   GNU General Public License version 2.0 (GPL)
**
**   as published by the Free Software Foundation
**   http://www.gnu.org/licenses/gpl-2.0.txt and appearing in the file
**   LICENSE.GPL included in the packaging of this file. 
**
** or the
**  
**   Agreement for Purchase and Licensing
**
**   as offered by Software- und Organisations-Service GmbH
**   in the respective terms of supply that ship with this file.
**
** THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
** IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
** THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
** CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
** SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
** CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
** ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
** POSSIBILITY OF SUCH DAMAGE.
********************************************************** end of preamble*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 11:12:34 AM MESZ 
//


package sos.scheduler.InstallationService.batchInstallationModel.installations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}schedulerId"/>
 *         &lt;element ref="{}licence"/>
 *         &lt;element ref="{}licenceOptions" minOccurs="0"/>
 *         &lt;element ref="{}schedulerPort"/>
 *         &lt;element ref="{}schedulerAllowedHost"/>
 *         &lt;element ref="{}installPath"/>
 *         &lt;element ref="{}UserPathPanelElement"/>
 *         &lt;element ref="{}host"/>
 *         &lt;element ref="{}ftp"/>
 *         &lt;element ref="{}ssh"/>
 *       &lt;/sequence>
 *       &lt;attribute name="lastRun" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "schedulerId",
    "licence",
    "licenceOptions",
    "schedulerPort",
    "schedulerAllowedHost",
    "installPath",
    "userPathPanelElement",
    "host",
    "ftp",
    "ssh"
})
@XmlRootElement(name = "installation")
public class Installation {

    @XmlElement(required = true)
    protected String schedulerId;
    @XmlElement(required = true)
    protected String licence;
    protected String licenceOptions;
    protected short schedulerPort;
    @XmlElement(required = true)
    protected String schedulerAllowedHost;
    @XmlElement(required = true)
    protected String installPath;
    @XmlElement(name = "UserPathPanelElement", required = true)
    protected String userPathPanelElement;
    @XmlElement(required = true)
    protected String host;
    @XmlElement(required = true)
    protected Ftp ftp;
    @XmlElement(required = true)
    protected Ssh ssh;
    @XmlAttribute(required = true)
    protected String lastRun;

    /**
     * Gets the value of the schedulerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchedulerId() {
        return schedulerId;
    }

    /**
     * Sets the value of the schedulerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchedulerId(String value) {
        this.schedulerId = value;
    }

    /**
     * Gets the value of the licence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicence() {
        return licence;
    }

    /**
     * Sets the value of the licence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicence(String value) {
        this.licence = value;
    }

    /**
     * Gets the value of the licenceOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenceOptions() {
        return licenceOptions;
    }

    /**
     * Sets the value of the licenceOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenceOptions(String value) {
        this.licenceOptions = value;
    }

    /**
     * Gets the value of the schedulerPort property.
     * 
     */
    public short getSchedulerPort() {
        return schedulerPort;
    }

    /**
     * Sets the value of the schedulerPort property.
     * 
     */
    public void setSchedulerPort(short value) {
        this.schedulerPort = value;
    }

    /**
     * Gets the value of the schedulerAllowedHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchedulerAllowedHost() {
        return schedulerAllowedHost;
    }

    /**
     * Sets the value of the schedulerAllowedHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchedulerAllowedHost(String value) {
        this.schedulerAllowedHost = value;
    }

    /**
     * Gets the value of the installPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstallPath() {
        return installPath;
    }

    /**
     * Sets the value of the installPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstallPath(String value) {
        this.installPath = value;
    }

    /**
     * Gets the value of the userPathPanelElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserPathPanelElement() {
        return userPathPanelElement;
    }

    /**
     * Sets the value of the userPathPanelElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserPathPanelElement(String value) {
        this.userPathPanelElement = value;
    }

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost(String value) {
        this.host = value;
    }

    /**
     * Gets the value of the ftp property.
     * 
     * @return
     *     possible object is
     *     {@link Ftp }
     *     
     */
    public Ftp getFtp() {
        return ftp;
    }

    /**
     * Sets the value of the ftp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ftp }
     *     
     */
    public void setFtp(Ftp value) {
        this.ftp = value;
    }

    /**
     * Gets the value of the ssh property.
     * 
     * @return
     *     possible object is
     *     {@link Ssh }
     *     
     */
    public Ssh getSsh() {
        return ssh;
    }

    /**
     * Sets the value of the ssh property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ssh }
     *     
     */
    public void setSsh(Ssh value) {
        this.ssh = value;
    }

    /**
     * Gets the value of the lastRun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastRun() {
        return lastRun;
    }

    /**
     * Sets the value of the lastRun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastRun(String value) {
        this.lastRun = value;
    }

}
